### ISSUE TITLE
Make tests for the todo app backend. CRUD

### ISSUE THREAD

**Issue by Dj-Viking** [Dj-Viking/vue3-typescript-bare-starter#5]
- [x] create tests that pass for the user queries and mutations
- [x] make CRUD tests for the user todos
    * [x] register a user and then the user creates a todo.
    * [x] todo gets the creatorId of the user in the context object, after they register. 
        - [ ] NTH need unexpired token to make a todo? 
    * [x] get the todos of a user as an array. (todos where creatorId === context.user.id?) 
    * [x] edit the todo after it is created
    * [x] delete the todo from the user's todoList array. 
    * [x] delete the user
